#6 Implements dark/light application themes support
Dshauchuk/pango pull request #18
Opened 2024-04-03 17:46 UTC by Fulllcrum

- Adds default/dark/light app themes support
- Fixes preselected language displaying at the settings view

2024-04-07 14:09 UTC, Dshauchuk requested changes

2024-04-07 14:09 UTC, Dshauchuk commented on src/Presentation/Desktop/Pango.Desktop.Uwp/Core/Utility/AppThemeHelper.cs
> +    private static async Task SetRequestedThemeAsync()
Do we need this as async?

2024-04-08 17:25 UTC, Fulllcrum commented on src/Presentation/Desktop/Pango.Desktop.Uwp/Core/Utility/AppThemeHelper.cs
> +    private static async Task SetRequestedThemeAsync()
Not really, updated

2024-04-08 18:05 UTC, Dshauchuk approved these changes
LGTM

2024-04-08 18:05 UTC, merged